force-app/main/default/objects/AppConfiguration__mdt/AppConfiguration__mdt.object-meta.xml
<CustomObject>
    <label>AppConfiguration</label>
    <pluralLabel>AppConfigurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/AppConfiguration__mdt/fields/ConfigurationFieldNumber__c.field-meta.xml
<CustomField>
    <fullName>ConfigurationFieldNumber__c</fullName>
    <label>ConfigurationFieldNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AppConfiguration__mdt/fields/ConfigurationFieldOne__c.field-meta.xml
<CustomField>
    <fullName>ConfigurationFieldOne__c</fullName>
    <label>ConfigurationFieldOne</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppConfiguration__mdt/fields/ConfigurationFieldTwo__c.field-meta.xml
<CustomField>
    <fullName>ConfigurationFieldTwo__c</fullName>
    <label>ConfigurationFieldTwo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppConfiguration__mdt/fields/IsConfigurationActive__c.field-meta.xml
<CustomField>
    <fullName>IsConfigurationActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsConfigurationActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AppConfiguration__mdt/fields/URLConfiguration__c.field-meta.xml
<CustomField>
    <fullName>URLConfiguration__c</fullName>
    <label>URLConfiguration</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/SingletonPattern/Example1/AppConfiguration.cls
public with sharing class AppConfiguration {
    // private static AppConfiguration instance - one per transaction
    private static AppConfiguration instance;
    
    private Map<String, Object> settingsCache;
    
    // private constructor to prevent instantiation from outside the class
    private AppConfiguration() {
        settingsCache = new Map<String, Object>();
        // Load settings from Custom Metadata or Custom Settings
        loadSettings();
    }

    // public static method to get the singleton instance
    public static AppConfiguration getInstance() {
        if (instance == null) {
            instance = new AppConfiguration();
        }
        return instance;
    }

    private void loadSettings() {
        // load settings from custom metadata and populate the settingsCache map
        // assuming that there is only one record with the configuration settings
        List<AppConfiguration__mdt> appConfigurations = [SELECT ConfigurationFieldNumber__c, ConfigurationFieldOne__c, ConfigurationFieldTwo__c, URLConfiguration__c FROM AppConfiguration__mdt WHERE IsConfigurationActive__c = true];
        if (appConfigurations.isEmpty()) {
            throw new AppConfigurationException('No active configuration found.');
        }

        if (appConfigurations.size() > 1) {
            throw new AppConfigurationException('Multiple active configurations found. Please ensure only one configuration is active.');
        }

        AppConfiguration__mdt appConfiguration = appConfigurations[0];
        settingsCache.put('ConfigurationFieldNumber', appConfiguration.ConfigurationFieldNumber__c);
        settingsCache.put('ConfigurationFieldOne', appConfiguration.ConfigurationFieldOne__c);
        settingsCache.put('ConfigurationFieldTwo', appConfiguration.ConfigurationFieldTwo__c);
        settingsCache.put('URLConfiguration', appConfiguration.URLConfiguration__c);
    }

    public Object getSetting(String key) {
        return settingsCache.get(key);
    }

    public class AppConfigurationException extends Exception {}

    // Usage examples:

    //Object configurationFieldOne = AppConfiguration.getInstance().getSetting('ConfigurationFieldOne');
    //System.debug(configurationFieldOne);

    //Object configurationFieldNumber = AppConfiguration.getInstance().getSetting('ConfigurationFieldNumber');
    //System.debug(configurationFieldNumber);
}